version: 2
jobs:
  build:
    docker:
    - image: alpine:latest
    steps:
    - run:
        name: 'APK: Add repository.'
        command: printf "\n%s\n" "http://nl.alpinelinux.org/alpine/edge/testing" >>
          /etc/apk/repositories
    - run:
        name: 'APK: Update cache.'
        command: apk update
    - run:
        name: 'Setup: Install build packages.'
        command: apk add bash python2
    - run:
        name: 'Setup: Install runtime packages.'
        command: apk add bat ripgrep
    - checkout
    - run:
        name: Build
        command: ./build.sh --minify=all
  test-snapshots:
    docker:
    - image: alpine:latest
    steps:
    - run:
        name: 'APK: Add repository.'
        command: printf "\n%s\n" "http://nl.alpinelinux.org/alpine/edge/testing" >>
          /etc/apk/repositories
    - run:
        name: 'APK: Update cache.'
        command: apk update
    - run:
        name: 'Setup: Install build packages.'
        command: apk add bash python2
    - run:
        name: 'Setup: Install runtime packages.'
        command: apk add bat ripgrep
    - checkout
    - run:
        name: Build
        command: ./build.sh --minify=all
    - run:
        name: 'Test: Snapshots'
        command: test/run.sh snapshot-test
  test-consistency:
    docker:
    - image: alpine:latest
    steps:
    - run:
        name: 'APK: Add repository.'
        command: printf "\n%s\n" "http://nl.alpinelinux.org/alpine/edge/testing" >>
          /etc/apk/repositories
    - run:
        name: 'APK: Update cache.'
        command: apk update
    - run:
        name: 'Setup: Install build packages.'
        command: apk add bash python2
    - run:
        name: 'Setup: Install runtime packages.'
        command: apk add bat ripgrep
    - checkout
    - run:
        name: Build
        command: ./build.sh --minify=all
    - run:
        name: 'Test: Consistency'
        command: test/run.sh consistency-test
workflows:
  version: 2
  default:
    jobs:
    - build
    - test-snapshots:
        requires:
        - build
    - test-consistency:
        requires:
        - build

# Original config.yml file:
# version: 2.1
# 
# executors:
#     linux_alpine:
#         docker:
#             - image: alpine:latest
# 
# commands:
#     setup:
#         description: \"Set up the environment needed to test and run the scripts.\"
#         steps:
#             - run:
#                 name:   \"APK: Add repository.\"
#                 command: printf \"\\n%s\\n\" \"http://nl.alpinelinux.org/alpine/edge/testing\" >> /etc/apk/repositories
#             - run:
#                 name:    \"APK: Update cache.\"
#                 command: apk update
#             - run:
#                 name:    \"Setup: Install build packages.\"
#                 command: apk add bash python2
#             - run:
#                 name:    \"Setup: Install runtime packages.\"
#                 command: apk add bat ripgrep
# 
#     build:
#         description: \"Build the self-contained scripts.\"
#         parameters:
#             minify:
#                 type: string
#                 default: \"lib\"
#         steps:
#             - run:
#                 name:    \"Build\"
#                 command: ./build.sh --minify=<<parameters.minify>>
# 
# 
# jobs:
# 
#     build:
#         executor: linux_alpine
#         steps:
#             - setup
#             - checkout
#             - build:
#                 minify: \"all\"
# 
#     test-snapshots:
#         executor: linux_alpine
#         steps:
#             - setup
#             - checkout
#             - build:
#                 minify: \"all\"
#             - run:
#                 name:    \"Test: Snapshots\"
#                 command: test/run.sh snapshot-test
# 
#     test-consistency:
#         executor: linux_alpine
#         steps:
#             - setup
#             - checkout
#             - build:
#                 minify: \"all\"
#             - run:
#                 name:    \"Test: Consistency\"
#                 command: test/run.sh consistency-test
# 
# 
# workflows:
#     version: 2
#     default:
#         jobs:
#             - build
#             - test-snapshots:
#                 requires: [build]
#             - test-consistency:
#                 requires: [build]